baseURL = "/"
canonifyURLs = true
languageCode = "it-IT"
title = "💒 Andrew & Niki's Wedding"
show_comments = false

disableKinds = ["sitemap", "RSS"]

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    linkifyProtocol = "https"
    strikethrough = true
    table = true
    taskList = true
    typographer = true

  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = "github"

    [markup.goldmark.parser.attribute]
      block = false
      title = true

  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = false

[params]
  background_image_1 = "5marzo_andrew.jpg"
  background_image_2 = "santa_severa.jpg"
  background_image_3 = "oceano.jpg"
  background_image_4 = "sabbie_doro.jpg"
  background_image_5 = "5marzo_niki.jpg"
  background_image_6 = "patagonia.jpg"
  background_image_7 = "perito_moreno.jpg"
  background_image_8 = "iguazu_falls.jpg"
  background_image_9 = "tilcara.jpeg"
  background_image_10 = "salinas_grandes.jpg"
  background_image_11 = "ruta_68.jpg"
  background_image_12 = "cafayate.jpg"
  background_image_13 = "mendoza.jpg"
  background_image_14 = "casale_cover.jpg"
  background_image_15 = "5marzo_cover.jpg"
  background_image_16 = "patagonia_cover.jpg"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "travel"
    name = "Dove"
    url = "/travel/"
    weight = 2
