name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - wip  # Trigger workflow on push to the "wip" branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes if they are submodules
          fetch-depth: 0    # Fetch full history for .GitInfo and .Lastmod

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
        #   extended: true  # Enable extended version for SASS/SCSS support

      - name: Build the Hugo site
        run: hugo --minify  # Build site and optimize output

      - name: Add CNAME file to build output
        run: echo 'tittodano.github.io/wedding-website' > ./public/CNAME  # Set custom domain

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Publish Hugo's output directory
